name: Build App Sismos CDMX Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev unzip openjdk-17-jdk wget

    - name: Install Android SDK (commandlinetools)
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d tools
        yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Export ANDROID_HOME
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet buildozer cython

    - name: Initialize buildozer project
      run: |
        mkdir app_sismos_android
        cp app_sismos_cdmx_FINAL.py app_sismos_android/main.py
        cd app_sismos_android
        buildozer init
        sed -i 's/requirements = python3/requirements = flet/' buildozer.spec
        buildozer android debug clean || true

    - name: Build APK
      run: |
        cd app_sismos_android
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-sismos-cdmx-apk
        path: app_sismos_android/bin/*.apk
        retention-days: 30
